/** 设置：生成模型、周报/月报提示词模板、数据导入导出。 */
(function () {
  'use strict'

  var WC = window.WC
  var store = WC.store

  var view = { root: null }

  function render() {
    if (!view.root) return
    var s = store.state.settings
    var counts = store.state
    view.root.innerHTML =
      WC.L('<div class="page-head"><div><div class="page-title">设置</div><div class="page-sub">AI 报告由 AIPA 生成，使用与对话相同的模型与凭据</div></div></div>', '<div class="page-head"><div><div class="page-title">Settings</div><div class="page-sub">Reports are generated by AIPA using the same model and credentials as chat</div></div></div>') +
      '<div class="settings-grid">' +
        '<div class="card">' +
          WC.L('<div class="field"><label>生成模型</label><input class="input" data-f="model" placeholder="留空跟随对话当前模型" value="', '<div class="field"><label>Model</label><input class="input" data-f="model" placeholder="Leave empty to follow your chat model" value="') + WC.esc(s.model) + '">' +
            WC.L('<span class="hint">填写模型 ID（如 deepseek-flash）。模型属于某个已启用的网关 / 兼容接口时会走该提供商，否则由 Codex 生成；留空则跟随对话当前模型</span></div>', '<span class="hint">A model ID (e.g. deepseek-flash). A model owned by an enabled gateway / compatible provider runs on that provider, otherwise Codex generates it; leave empty to follow your chat model</span></div>') +
          WC.L('<div class="field"><label>周报提示词模板</label><textarea class="textarea" data-f="weeklyPrompt">', '<div class="field"><label>Weekly report prompt</label><textarea class="textarea" data-f="weeklyPrompt">') + WC.esc(s.weeklyPrompt) + '</textarea>' +
            WC.L('<span class="hint">可用变量：{{period}} 报告周期，{{material}} 任务与工作源素材</span></div>', '<span class="hint">Variables: {{period}} report period, {{material}} tasks and work-source material</span></div>') +
          WC.L('<div class="field"><label>月报提示词模板</label><textarea class="textarea" data-f="monthlyPrompt">', '<div class="field"><label>Monthly report prompt</label><textarea class="textarea" data-f="monthlyPrompt">') + WC.esc(s.monthlyPrompt) + '</textarea>' +
            WC.L('<span class="hint">月报素材为本月已生成周报的合并内容</span></div>', '<span class="hint">Monthly material is the month\'s weekly reports combined</span></div>') +
          WC.L('<div class="row" style="justify-content:flex-end"><button class="btn" data-act="reset">恢复默认提示词</button>', '<div class="row" style="justify-content:flex-end"><button class="btn" data-act="reset">Reset prompts</button>') +
            '<button class="btn btn-primary" data-act="save">' + WC.icon('save', 13) + WC.L('保存设置</button></div>', 'Save settings</button></div>') +
        '</div>' +
        '<div class="card">' +
          WC.L('<div class="section-title" style="margin-top:0">数据</div>', '<div class="section-title" style="margin-top:0">Data</div>') +
          '<div class="kv">' +
            WC.L('<span class="k">任务</span><span>', '<span class="k">Tasks</span><span>') + counts.tasks.length + WC.L(' 条</span>', '</span>') +
            WC.L('<span class="k">报告</span><span>', '<span class="k">Reports</span><span>') + counts.reports.length + WC.L(' 份</span>', '</span>') +
            WC.L('<span class="k">工作源</span><span>', '<span class="k">Work sources</span><span>') + counts.sources.length + WC.L(' 个</span>', '</span>') +
            WC.L('<span class="k">人天记录</span><span>', '<span class="k">Person-day entries</span><span>') + counts.personDays.length + WC.L(' 条</span>', '</span>') +
            WC.L('<span class="k">存储位置</span><span><code class="path">~/.aipa/plugin-data/aipa-work-calendar/</code></span>', '<span class="k">Location</span><span><code class="path">~/.aipa/plugin-data/aipa-work-calendar/</code></span>') +
          '</div>' +
          '<div class="row" style="margin-top:14px">' +
            '<button class="btn" data-act="export">' + WC.icon('download', 13) + WC.L('导出数据（JSON）</button>', 'Export (JSON)</button>') +
            '<button class="btn" data-act="import">' + WC.icon('upload', 13) + WC.L('导入数据</button>', 'Import</button>') +
            '<input type="file" accept=".json,application/json" data-f="file" class="hidden">' +
          '</div>' +
          WC.L('<div class="hint" style="margin-top:8px;font-size:11.5px;color:var(--muted)">导出文件不包含 GitHub Token；导入会覆盖当前全部数据。</div>', '<div class="hint" style="margin-top:8px;font-size:11.5px;color:var(--muted)">Exports exclude GitHub tokens; importing replaces all current data.</div>') +
        '</div>' +
      '</div>'
  }

  function onClick(e) {
    var btn = e.target.closest('[data-act]')
    if (!btn) return
    var act = btn.getAttribute('data-act')
    var f = function (n) { return view.root.querySelector('[data-f="' + n + '"]') }
    if (act === 'save') {
      store.saveSettings({ model: f('model').value.trim(), weeklyPrompt: f('weeklyPrompt').value, monthlyPrompt: f('monthlyPrompt').value })
        .then(function () { AIPA.toast('success', WC.L('设置已保存', 'Settings saved')) })
        .catch(function (err) { AIPA.toast('error', WC.L('保存失败：', 'Failed to save: ') + WC.errMsg(err)) })
    } else if (act === 'reset') {
      f('weeklyPrompt').value = store.DEFAULT_SETTINGS.weeklyPrompt
      f('monthlyPrompt').value = store.DEFAULT_SETTINGS.monthlyPrompt
      AIPA.toast('info', WC.L('已恢复默认提示词，点击「保存设置」生效', 'Default prompts restored — click "Save settings" to apply'))
    } else if (act === 'export') {
      var blob = new Blob([JSON.stringify(store.exportData(), null, 2)], { type: 'application/json' })
      var a = document.createElement('a')
      a.href = URL.createObjectURL(blob)
      a.download = 'work-calendar-' + WC.date.todayKey() + '.json'
      a.click()
      setTimeout(function () { URL.revokeObjectURL(a.href) }, 1000)
    } else if (act === 'import') {
      f('file').click()
    }
  }

  function onChange(e) {
    if (e.target.getAttribute('data-f') !== 'file' || !e.target.files.length) return
    var file = e.target.files[0]
    e.target.value = ''
    file.text().then(function (text) {
      var data = JSON.parse(text)
      return WC.confirm(WC.L('导入数据', 'Import data'), WC.L('导入会覆盖当前全部任务、报告、工作源与人天记录，确定继续吗？', 'Importing replaces all tasks, reports, work sources and person-day entries. Continue?'), { danger: true, okText: WC.L('覆盖导入', 'Replace') })
        .then(function (ok) {
          if (!ok) return
          return WC.attempt(function () { return store.importData(data) }).then(function () { AIPA.toast('success', WC.L('数据已导入', 'Data imported')) })
        })
    }).catch(function (err) { AIPA.toast('error', WC.L('导入失败：', 'Import failed: ') + WC.errMsg(err)) })
  }

  WC.views = WC.views || {}
  WC.views.settings = {
    mount: function (root) {
      view.root = root
      root.addEventListener('click', onClick)
      root.addEventListener('change', onChange)
      render()
    },
    unmount: function () {
      if (view.root) {
        view.root.removeEventListener('click', onClick)
        view.root.removeEventListener('change', onChange)
      }
      view.root = null
    },
    // Don't clobber unsaved edits in the prompt textareas on unrelated data changes
    refresh: function () {},
  }
})()
